#!/usr/bin/env ruby
require 'pathname'
require 'yaml'
require 'yard'

# fetch gem lists from yaml file for easy mod.
gem_lists = YAML.load(File.read(__dir__ + '/gem-lists.yaml'))

# library to include configuration
location_list = gem_lists.keys.map do |lib|
  Gem.find_files(lib).map do |lib_file|
    dir = Pathname.new File.dirname(lib_file)
    new_dir = dir.relative_path_from(Pathname.pwd)
    unless new_dir.to_s.include?('../')
      dir = new_dir
    end
    dir.to_s
  end
end.flatten

# convert available path into globable string
glob_path = sprintf("{%s}/%s",
  location_list.map do |dir|
    dir.gsub(/[*]{1,2}|[?]|[\[\]{},]/) { |s| "\\#{s}" }
  end.join(','),
  '**/*.rb',
)

# apply extra yard require from here
gem_lists.each do |gem_name, gem_opt|
  lib_name = gem_opt.fetch('lib', gem_name)
  next unless gem_opt.key?('yard')
  yard_lib = File.join(lib_name, gem_opt['yard'])
  require yard_lib
end

# pass globbable string to arguments and process
argv = ARGV.dup
argv << glob_path

YARD::CLI::CommandParser.run(*argv)
