name: Update Repository Documents
on:
  push:
    branches:
    - master
    paths:
    - 'Gemfile'
    - 'gem-lists.yaml'
    - '.github/workflows/write-docs.yaml'
    - 'bin/**'
    - 'yard-config/**'
  repository_dispatch:
    types:
    - update-gem
  workflow_dispatch:
    ref: master
concurrency:
  group: ci-write-docs
  cancel-in-progress: true
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GEM_REPO_ACCESS }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Access Documentation Worktree
      run: |
        git worktree add doc docs
        if [[ -f doc/.gemcache ]]; then
          mv doc/.gemcache .
          rm -dr doc/**/*
          mv .gemcache doc
        else
          rm -dr doc/**/*
        fi
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7
    - name: Check Library Cache
      run: |
        bundle exec ruby bin/process-gemcache
        if [[ -f doc/.gemcache ]]; then
          set +e
          diff -iEbZwBaq .gemcache doc/.gemcache
          echo "IGNORE_DOC_OVERRIDE=$?" >> $GITHUB_ENV
          set -e
        else
          echo "IGNORE_DOC_OVERRIDE=1" >> $GITHUB_ENV
        fi
    - name: YARD Gem Stats
      run: |
        bundle exec ruby bin/run-yard stats --list-undoc
    - name: YARD Gem Write
      if: ${{ env.IGNORE_DOC_OVERRIDE == '1' }}
      run: |
        bundle exec ruby bin/run-yard doc -r yard-config/README.md \
          -p yard-config/templates/reidoc \
          --hide-void-return
        mv .gemcache doc/.gemcache
    - name: Commit to Docs
      if: ${{ env.IGNORE_DOC_OVERRIDE == '1' }}
      working-directory: ./doc
      continue-on-error: true
      run: |
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "$(date -u +'doc generated at %Y%m%d.%H:%M:%S')"
        git push
