name: Update Repository Documents
on:
  push:
    branches:
    - master
    paths:
    - 'run-yard'
    - 'Gemfile'
    - 'gem-lists.yaml'
    - '.github/workflows/write-docs.yaml'
    - 'yard-config/**'
  repository_dispatch:
    types:
    - update-gem
  workflow_dispatch:
concurrency:
  group: ci-write-docs
  cancel-in-progress: true
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GEM_REPO_ACCESS }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Access Documentation Worktree
      run: |
        git worktree add doc docs
        rm -dr doc/**/*
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7
    - name: Check Vendor Cache
      run: |
        [[ ! -f vendor/bundle/.write-cached ]]
        echo "IGNORE_DOC_OVERRIDE=$?" >> $GITHUB_ENV
    - name: Install Gems
      run: |
        bundle install
    - name: YARD Gem Stats
      run: |
        bundle exec ruby run-yard stats --list-undoc
    - name: YARD Gem Write
      if: ${{ env.IGNORE_DOC_OVERRIDE == '0' }}
      run: |
        bundle exec ruby run-yard doc -r yard-config/README.md \
          -p yard-config/templates/reidoc \
          --hide-void-return
        touch vendor/bundle/.write-cached
    - name: Commit to Docs
      working-directory: ./doc
      continue-on-error: true
      run: |
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "$(date -u +'doc generated at %Y%m%d.%H:%M:%S')"
        git push
